### ISSUE TITLE
I can't add Social Profiles

### ISSUE THREAD

**Issue by Javi-MC** [bic-ed/Multiverse#11]
Hi all!!

After updating the Multiverse theme to version 2.2, when I enter the theme options, the boxes or buttons to add social profiles do not appear.

![image](https://github.com/bic-ed/Multiverse/assets/139554329/f5d4c44a-a232-4d24-ba44-dc6c29c82d10)

**Comment by bic-ed** [comment]
Which version of Zenphoto are you running?

**Comment by Javi-MC** [comment]
Hi @bic-ed 

I am using version 1.6
 
I don't know if it has anything to do with it but I have returned to version 2.1 of Multiverse and the Social profiles options appear, but when I add one and click save, a 500 error appears in the file /multiverse/ajax/save_options.php

**Comment by bic-ed** [comment]
Ok, then something went wrong in the automatic process of renaming options. Since some options name were conflicting in some circumstances with other ZP or themes ones, I've added a prefix for multiverse options in v2.2, but the renaming process should run behind the scene when you visit the options page for the first time after upgrading. See the readme:
> NOTICE: Since option names were changed in version 2.2, if upgrading from a previuos version you must visit the theme options page to allow automatic import of existing settings.

The file save_options.php is not there anymore in v2.2, but it should be there in v2.1, so probably you didn't restore all the files of the old version.

But lets try to solve the problem. Do you have access to the database?

**Comment by Javi-MC** [comment]
Thanks! 

The problem with save_options.php has been when going back to version 2.1 and trying to add a new social profile

Yes, I have access to the database.

**Comment by bic-ed** [comment]
> The problem with save_options.php has been when going back to version 2.1 and trying to add a new social profile

Weird, It should be there in v2.1. Anyway v2.1 won't work properly with ZP 1.6+, so let's try to install Multiverse v2.2.
I need some information to figure out how to help.
Search for "multiverse" in the database. Do you get an option named `multiverse_social_contacts` in the results or just `social_contacts`?

**Comment by Javi-MC** [comment]
There is an option called social_content with social profiles and the option social_contacts with value 1

**Comment by bic-ed** [comment]
Ok, then for some reasons it never updated the options names. You can try again following these steps.

1. Remove the entire `multiverse` folder from the `themes` folder of your ZP installation
2. Upload there just the new `multiverse` folder that you find in the zip file of Multiverse v2.2
3. Clean the browser cache, just to be sure it does not use the old version of JavaScript from v2.1
4. Visit the theme options page

If that does not work again, I'll give you instructions to manually update the multiverse's options names in the database.

**Comment by Javi-MC** [comment]
I have deleted the folder and unzipped the theme zip again, after clearing the browser cache everything seems to work correctly.
The multiverse_social_contacts and multiverse_social_content options now appear in the database

Thanks a lot!

**Comment by bic-ed** [comment]
Great, glad it worked!
