### ISSUE TITLE
No need to require functions.php

### ISSUE THREAD

**Issue by fretzl** [bic-ed/Multiverse#3]
There is no need to "require" functions.php on line 5 of themeoptions.php.
The file is loaded automatically.

**Comment by bic-ed** [comment]
Thanks!
The reason why that line is there is that I started building theme options from `themeoptions.php` of ZP basic theme, where that line is still present actually! 
https://github.com/zenphoto/zenphoto/blob/342a19cb48fffc217f17e892147ea71c1e8fef80/themes/basic/themeoptions.php#L12
So it should be removed from there too?

**Comment by fretzl** [comment]
Sorry, my mistake. It's just that for you theme it's not necessary. 
The Basic and Garland themes do indeed need to "require" functions.php for certain custom options.
I thought it was loaded automatically for all theme files but apparently not for themeoptions.php.

**Comment by bic-ed** [comment]
Thanks, I removed that line anyway and it doesn't harms.
367535f144bf79926b36fe43c1a190862109d3e8
